#!/bin/bash

# display usage information
if [ -z "$1" ]; then
  echo "Usage: $(basename "$0") file.m3u8 [output.mp4]"
  exit 1
fi

if [ ! -f "$1" ]; then
  echo "Error: File \"$1\" not found."
  exit 1
fi

# set mp4 output filename
if [ -z "$2" ]; then
  output="output.mp4"
else
  output="$2"
fi
while [[ "$output" == *"." ]]; do
  output="${output%.}"
done
ext="$(echo "${output: -4}" | tr '[:upper:]' '[:lower:]')"
if [ "$ext" != ".mp4" ]; then
  output="${output}.mp4"
fi

# merge all ts files to mp4 file
ffmpeg -y -allowed_extensions ALL -protocol_whitelist "file,crypto,data" -i "$1" -c copy "$output"
